[package]
name = "osc-cost"
version = "0.1.0"
edition = "2021"
authors = ["OpenSource Team <opensource@outscale.com>"]
license = "BSD-3-Clause"
description = "osc-cost helps measuring Outscale infrastructure costs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.18", features = ["derive"] }
csv = "1.1.6"
env_logger = "0.9.3"
http = "0.1.21"
lazy_static = "1.4.0"
log = "0.4.17"
outscale_api = { version = "1.2.0", features = ["rustls-tls"], default-features = false }
rand = "0.8.5"
regex = "1.6.0"
secrecy = "0.8.0"
serde = "1.0.147"
serde_json = "1.0.87"
